import random
from decimal import Decimal
from datetime import date, timedelta

from db import db
from models.purchase import Purchase
from models.purchase_item import PurchaseItem
from models.product_variant import ProductVariant
from models.supplier import Supplier
from models.user import User


PAYMENT_METHODS = [
    "Cash",
    "Bank Transfer",
    "Mobile Money",
    "Cheque"
]

STATUSES = [
    "Completed",
    "Completed",
    "Completed",
    "Completed",
    "Pending"
]


def seed_purchases(number_of_purchases=100):
    """
    Creates realistic purchase records and updates stock.
    """

    suppliers = Supplier.query.all()
    variants = ProductVariant.query.all()

    admin = User.query.filter_by(username="admin").first()

    if not admin:
        raise Exception("Admin user not found.")

    if not suppliers:
        raise Exception("No suppliers found.")

    if not variants:
        raise Exception("No product variants found.")

    for purchase_index in range(1, number_of_purchases + 1):

        supplier = random.choice(suppliers)

        purchase = Purchase(
            purchase_number=f"PUR-2026{purchase_index:05d}",
            supplier_id=supplier.id,
            purchase_date=date.today() - timedelta(days=random.randint(0, 365)),
            invoice_number=f"INV-{purchase_index:06d}",
            payment_method=random.choice(PAYMENT_METHODS),
            status=random.choice(STATUSES),
            notes="Demo purchase generated by seeder.",
            created_by=admin.id,
            total_amount=Decimal("0.00")
        )

        db.session.add(purchase)
        db.session.flush()   # Gives purchase.id before commit

        purchase_total = Decimal("0.00")

        selected_variants = random.sample(
            variants,
            random.randint(2, min(8, len(variants)))
        )

        for variant in selected_variants:

            quantity = random.randint(2, 15)

            unit_cost = Decimal(str(variant.buying_price))

            subtotal = unit_cost * quantity

            item = PurchaseItem(
                purchase_id=purchase.id,
                product_variant_id=variant.id,
                quantity=quantity,
                unit_cost=unit_cost,
                subtotal=subtotal
            )

            db.session.add(item)

            # Increase stock
            variant.quantity += quantity

            purchase_total += subtotal

        purchase.total_amount = purchase_total

    db.session.commit()

    print(f"✓ {number_of_purchases} purchases created successfully.")