"""Create product module

Revision ID: 2ba2497e4e93
Revises: c5569e6533f0
Create Date: 2026-07-04 17:10:11.766386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ba2497e4e93'
down_revision = 'c5569e6533f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.Enum('Brand New', 'Refurbished', 'Used Grade A', 'Used Grade B', name='product_condition'), nullable=False))
        batch_op.alter_column('buying_price',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
        batch_op.alter_column('selling_price',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.alter_column('selling_price',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('buying_price',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
