"""Create suppliers table

Revision ID: 40c228af2b60
Revises: ad588fcd155b
Create Date: 2026-07-21 13:03:53.706536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c228af2b60'
down_revision = 'ad588fcd155b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('imeis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.String(length=30), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('In Stock', 'Reserved', 'Sold', 'Returned', 'Damaged', name='imei_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imei'),
    sa.UniqueConstraint('serial_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imeis')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
