"""add trade in tables

Revision ID: 6b721c934283
Revises: 4051c1b71b71
Create Date: 2026-08-01 12:37:19.729303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b721c934283'
down_revision = '4051c1b71b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_in_number', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('alternative_phone', sa.String(length=30), nullable=True),
    sa.Column('business_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('national_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('trade_in_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Accepted', 'Rejected', 'Cancelled', name='trade_in_status'), nullable=False),
    sa.Column('total_trade_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_paid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('topup_received', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_in_number')
    )
    op.create_table('trade_in_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_in_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('imei_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('battery_health', sa.Integer(), nullable=True),
    sa.Column('network_lock', sa.String(length=100), nullable=True),
    sa.Column('icloud_status', sa.String(length=100), nullable=True),
    sa.Column('frp_status', sa.String(length=100), nullable=True),
    sa.Column('screen_condition', sa.String(length=100), nullable=True),
    sa.Column('back_condition', sa.String(length=100), nullable=True),
    sa.Column('frame_condition', sa.String(length=100), nullable=True),
    sa.Column('camera_condition', sa.String(length=100), nullable=True),
    sa.Column('charging_port', sa.String(length=100), nullable=True),
    sa.Column('speaker_status', sa.String(length=100), nullable=True),
    sa.Column('microphone_status', sa.String(length=100), nullable=True),
    sa.Column('face_id_status', sa.String(length=100), nullable=True),
    sa.Column('fingerprint_status', sa.String(length=100), nullable=True),
    sa.Column('volume_buttons', sa.String(length=100), nullable=True),
    sa.Column('power_button', sa.String(length=100), nullable=True),
    sa.Column('wifi_status', sa.String(length=100), nullable=True),
    sa.Column('bluetooth_status', sa.String(length=100), nullable=True),
    sa.Column('sim_status', sa.String(length=100), nullable=True),
    sa.Column('vibration_status', sa.String(length=100), nullable=True),
    sa.Column('flashlight_status', sa.String(length=100), nullable=True),
    sa.Column('offered_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('final_trade_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('default_selling_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('estimated_profit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('box_received', sa.Boolean(), nullable=True),
    sa.Column('charger_received', sa.Boolean(), nullable=True),
    sa.Column('cable_received', sa.Boolean(), nullable=True),
    sa.Column('adapter_received', sa.Boolean(), nullable=True),
    sa.Column('earphones_received', sa.Boolean(), nullable=True),
    sa.Column('case_received', sa.Boolean(), nullable=True),
    sa.Column('screen_protector', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['imei_id'], ['imeis.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['trade_in_id'], ['trade_ins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_in_items')
    op.drop_table('trade_ins')
    # ### end Alembic commands ###
