"""add system settings

Revision ID: 7fa3586f81a9
Revises: 6187b6022bbb
Create Date: 2026-07-28 15:23:56.175373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa3586f81a9'
down_revision = '6187b6022bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('date_format', sa.String(length=30), nullable=False),
    sa.Column('default_minimum_stock', sa.Integer(), nullable=False),
    sa.Column('enable_low_stock_alerts', sa.Boolean(), nullable=False),
    sa.Column('prevent_negative_stock', sa.Boolean(), nullable=False),
    sa.Column('require_customer_on_sale', sa.Boolean(), nullable=False),
    sa.Column('require_imei_when_available', sa.Boolean(), nullable=False),
    sa.Column('allow_price_override', sa.Boolean(), nullable=False),
    sa.Column('receipt_footer', sa.String(length=255), nullable=True),
    sa.Column('show_imei_on_receipt', sa.Boolean(), nullable=False),
    sa.Column('show_cashier_on_receipt', sa.Boolean(), nullable=False),
    sa.Column('auto_update_buying_price', sa.Boolean(), nullable=False),
    sa.Column('records_per_page', sa.Integer(), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
