"""Link IMEIs to purchase items

Revision ID: 98f8f02a656b
Revises: d222813d62ce
Create Date: 2026-08-15 14:20:18.057824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f8f02a656b'
down_revision = 'd222813d62ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imeis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'purchase_items', ['purchase_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imeis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('purchase_item_id')

    # ### end Alembic commands ###
